### ISSUE TITLE
[Feature Request]: Support adding visit animation styles to `[data-swup-fragment]`

### ISSUE THREAD

**Issue by hirasso** [swup/fragment-plugin#87]
### Describe the problem 🧐

Currently, adding animations to fragment elements is only possible via the `id` or `class` element:

```css
#archive.is-changing {
  transition: opacity 100ms ease-in;
  opacity: 1;
}
#archive.is-animating {
  opacity: 0;
}
#archive.is-rendering {
  transition: opacity 250ms ease-out;
}
```

or: 

```css
.my-fragment.is-changing {
  transition: opacity 100ms ease-in;
  opacity: 1;
}
.my-fragment.is-animating {
  opacity: 0;
}
.my-fragment.is-rendering {
  transition: opacity 250ms ease-out;
}
```

It would be convenient to target currently changing `[data-swup-fragment]` elements directly, as a catch-all solution for fragment visits:

```css
[data-swup-fragment].is-changing {
  transition: opacity 100ms ease-in;
  opacity: 1;
}
[data-swup-fragment].is-animating {
  opacity: 0;
}
[data-swup-fragment].is-rendering {
  transition: opacity 250ms ease-out;
}
```

This currently works for the ? `out` phase, but fails during the `in` phase. There seems to be a timing issue when the attributes are added after a visit.

### Describe the propsed solution 😎

We need to see if it's feasible to add the `[data-swup-fragment]` attribute before the `in` animation starts.

### Alternatives considered 🤔

Do nothing, keep using `id` and `class` attributes.

### How important is this feature to you? 🧭

Nice to have

### Checked all these? 📚

- [x] I have read and searched the [official docs](https://swup.js.org)
- [x] I have checked [discussions](https://github.com/orgs/swup/discussions) and [existing issues](https://github.com/issues?q=is:issue+org:swup) for related problems
- [x] I agree to follow this project's [Code of Conduct](https://github.com/swup/.github/blob/main/CODE_OF_CONDUCT.md)
- [x] I have provided all necessary information to the best of my knowledge
